version: '3'

networks:
  proxy:
    external: true

services:
  nginx:
    image: jwilder/nginx-proxy:alpine-0.7.0
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    networks:
      - proxy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - node.name=poces
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - VIRTUAL_HOST=elastic.brunopadz.io
      - VIRTUAL_PORT=9200
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - proxy
      - default

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.2
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash:/etc/logstash/conf.d
      - ./logstash/patterns:/opt/logstash/patterns
    networks:
      - proxy
      - default
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - VIRTUAL_HOST=kibana.brunopadz.io
      - VIRTUAL_PORT=5601
    networks:
      - proxy
      - default
    depends_on:
      - elasticsearch
